name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y pwsh

    - name: Build
      run: make build

    - name: Package
      run: make package
